//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_log_wpnb
    {
        public int id { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public string target { get; set; }
        public string achievement { get; set; }
    }
}
