//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_log_pro
    {
        public int id { get; set; }
        public Nullable<int> id_daily_log { get; set; }
        public string wo_number { get; set; }
        public string work_to_be_performed { get; set; }
        public Nullable<byte> sap_status { get; set; }
        public string pro_time { get; set; }
    
        public virtual daily_log daily_log { get; set; }
    }
}
