//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_log_power_stations
    {
        public int id { get; set; }
        public Nullable<int> id_daily_log { get; set; }
        public string power_station_time { get; set; }
        public string power_station_unit { get; set; }
        public string power_station_activity { get; set; }
    
        public virtual daily_log daily_log { get; set; }
    }
}
