//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_log_weekly_target
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> shift { get; set; }
        public string target_unit_1 { get; set; }
        public string target_unit_2 { get; set; }
    }
}
