//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discipline
    {
        public int id { get; set; }
        public string title { get; set; }
        public int id_tag_type { get; set; }
    
        public virtual tag_types tag_types { get; set; }
    }
}
