//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_dept
    {
        public employee_dept()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int id { get; set; }
        public string dept_name { get; set; }
        public Nullable<int> plant_id { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
        public virtual plant plant { get; set; }
    }
}
