//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class excavation
    {
        public excavation()
        {
            this.excavation_disposal_location = new HashSet<excavation_disposal_location>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_ptw { get; set; }
        public string ex_no { get; set; }
        public string work_location { get; set; }
        public string supervisor { get; set; }
        public string requestor { get; set; }
        public Nullable<int> total_crew { get; set; }
        public string purpose { get; set; }
        public Nullable<System.DateTime> estimate_start_date { get; set; }
        public Nullable<System.DateTime> estimate_end_date { get; set; }
        public string pre_screening_spv { get; set; }
        public string pre_screening_ei { get; set; }
        public string pre_screening_fac { get; set; }
        public string pre_screening_fo { get; set; }
        public string excavation_performed { get; set; }
        public string excavation_method { get; set; }
        public string equipment { get; set; }
        public string soil_volume { get; set; }
        public string disposal_location { get; set; }
        public string disposal_type { get; set; }
        public string supervisor_signature { get; set; }
        public string supervisor_delegate { get; set; }
        public Nullable<System.DateTime> supervisor_signature_date { get; set; }
        public string enviro_officer { get; set; }
        public string enviro_officer_signature { get; set; }
        public string enviro_officer_delegate { get; set; }
        public Nullable<System.DateTime> enviro_officer_signature_date { get; set; }
        public string facilities { get; set; }
        public string facilities_signature { get; set; }
        public string facilities_delegate { get; set; }
        public Nullable<System.DateTime> facilities_signature_date { get; set; }
        public string ei { get; set; }
        public string ei_signature { get; set; }
        public string ei_delegate { get; set; }
        public Nullable<System.DateTime> ei_signature_date { get; set; }
        public string requestor_signature { get; set; }
        public string requestor_delegate { get; set; }
        public Nullable<System.DateTime> requestor_signature_date { get; set; }
        public string facility_owner { get; set; }
        public string facility_owner_signature { get; set; }
        public string facility_owner_delegate { get; set; }
        public Nullable<System.DateTime> facility_owner_signature_date { get; set; }
        public string screening_remark { get; set; }
        public string approval_note { get; set; }
        public string can_enviro_officer_signature { get; set; }
        public string can_enviro_officer_delegate { get; set; }
        public Nullable<System.DateTime> can_enviro_officer_signature_date1 { get; set; }
        public string can_facilities_signature { get; set; }
        public string can_facilities_delegate { get; set; }
        public Nullable<System.DateTime> can_facilities_signature_date { get; set; }
        public string can_ei_signature { get; set; }
        public string can_ei_delegate { get; set; }
        public Nullable<System.DateTime> can_ei_signature_date { get; set; }
        public string can_requestor_signature { get; set; }
        public string can_requestor_delegate { get; set; }
        public Nullable<System.DateTime> can_requestor_signature_date { get; set; }
        public string can_facility_owner_signature { get; set; }
        public string can_facility_owner_delegate { get; set; }
        public Nullable<System.DateTime> can_facility_owner_signature_date { get; set; }
        public string cancellation_note { get; set; }
        public Nullable<int> status { get; set; }
        public string can_supervisor_signature { get; set; }
        public string can_supervisor_delegate { get; set; }
        public Nullable<System.DateTime> can_supervisor_signature_date { get; set; }
    
        public virtual permit_to_work permit_to_work { get; set; }
        public virtual ICollection<excavation_disposal_location> excavation_disposal_location { get; set; }
    }
}
