//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fire_impairment
    {
        public int id { get; set; }
        public string purpose { get; set; }
        public string area_affected { get; set; }
        public string requestor { get; set; }
        public string fire_watch { get; set; }
        public string screening_spv { get; set; }
        public string screening_so { get; set; }
        public string screening_fo { get; set; }
        public string screening_remark { get; set; }
        public string acc_work_leader { get; set; }
        public string acc_work_leader_signature { get; set; }
        public string acc_work_leader_delegate { get; set; }
        public string acc_fire_watch_signature { get; set; }
        public string acc_fire_wacth_delegate { get; set; }
        public string acc_so { get; set; }
        public string acc_so_signature { get; set; }
        public string acc_so_delegate { get; set; }
        public string acc_fo { get; set; }
        public string acc_fo_delegate { get; set; }
        public string acc_fo_signature { get; set; }
        public string spv { get; set; }
        public string acc_dept_head { get; set; }
        public string acc_dept_head_delegate { get; set; }
        public string acc_dept_head_signature { get; set; }
        public string cancel_spv { get; set; }
        public string cancel_so { get; set; }
        public string cancel_fo { get; set; }
        public string cancel_remark { get; set; }
        public string cancel_work_leader_delegate { get; set; }
        public string cancel_work_leader_signature { get; set; }
        public string cancel_fire_watch_delegate { get; set; }
        public string cancel_fire_watch_signature { get; set; }
        public string cancel_so_delegate { get; set; }
        public string cancel_so_signature { get; set; }
        public string cancel_fo_delegate { get; set; }
        public string cancel_fo_signature { get; set; }
        public string cancel_dept_head_delegate { get; set; }
        public string cancel_dept_head_signature { get; set; }
        public Nullable<int> id_ptw { get; set; }
        public Nullable<int> status { get; set; }
        public string fi_no { get; set; }
        public Nullable<byte> is_extend { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual permit_to_work permit_to_work { get; set; }
    }
}
