//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hot_work
    {
        public int id { get; set; }
        public string hw_no { get; set; }
        public string fire_watch { get; set; }
        public string purpose { get; set; }
        public string work_leader { get; set; }
        public Nullable<System.DateTime> validity_period_start { get; set; }
        public Nullable<System.DateTime> validity_period_end { get; set; }
        public string screening_spv { get; set; }
        public string screening_fo { get; set; }
        public string screening_1 { get; set; }
        public string screening_2 { get; set; }
        public string screening_3 { get; set; }
        public string screening_4 { get; set; }
        public string screening_5 { get; set; }
        public string screening_6 { get; set; }
        public string screening_7 { get; set; }
        public Nullable<int> id_ptw { get; set; }
        public string notes { get; set; }
        public string methane_result { get; set; }
        public string o2_result { get; set; }
        public string h2s_result { get; set; }
        public string co_result { get; set; }
        public string other_gas { get; set; }
        public string other_result { get; set; }
        public string acc_work_leader_approve { get; set; }
        public string acc_supervisor_approve { get; set; }
        public string acc_supervisor { get; set; }
        public string acc_supervisor_delegate { get; set; }
        public string acc_fire_watch { get; set; }
        public string acc_fire_watch_delegate { get; set; }
        public string acc_fire_watch_approve { get; set; }
        public string acc_fo { get; set; }
        public string acc_fo_delegate { get; set; }
        public string acc_fo_approve { get; set; }
        public string acc_gas_tester { get; set; }
        public string acc_gas_tester_approve { get; set; }
        public string acc_work_representative_approve { get; set; }
        public string can_work_leader_approve { get; set; }
        public string can_supervisor_approve { get; set; }
        public string can_supervisor { get; set; }
        public string can_supervisor_delegate { get; set; }
        public string can_fire_watch { get; set; }
        public string can_fire_watch_delegate { get; set; }
        public string can_fire_watch_approve { get; set; }
        public string can_fo { get; set; }
        public string can_fo_delegate { get; set; }
        public string can_fo_approve { get; set; }
        public Nullable<System.DateTime> ext_datetime_1 { get; set; }
        public string ext_lel_1 { get; set; }
        public string ext_o2_1 { get; set; }
        public string ext_h2s_1 { get; set; }
        public string ext_co_1 { get; set; }
        public string ext_other_1 { get; set; }
        public string ext_gas_tester_1 { get; set; }
        public string ext_gas_tester_approve_1 { get; set; }
        public string ext_work_leader_1 { get; set; }
        public string ext_work_leader_approve_1 { get; set; }
        public string ext_fo_1 { get; set; }
        public string ext_fo_delegate_1 { get; set; }
        public string ext_fo_approve_1 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_1 { get; set; }
        public string ext_remark_1 { get; set; }
        public Nullable<System.DateTime> ext_datetime_2 { get; set; }
        public string ext_lel_2 { get; set; }
        public string ext_o2_2 { get; set; }
        public string ext_h2s_2 { get; set; }
        public string ext_co_2 { get; set; }
        public string ext_other_2 { get; set; }
        public string ext_gas_tester_2 { get; set; }
        public string ext_gas_tester_approve_2 { get; set; }
        public string ext_work_leader_2 { get; set; }
        public string ext_work_leader_approve_2 { get; set; }
        public string ext_fo_2 { get; set; }
        public string ext_fo_delegate_2 { get; set; }
        public string ext_fo_approve_2 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_2 { get; set; }
        public string ext_remark_2 { get; set; }
        public Nullable<System.DateTime> ext_datetime_3 { get; set; }
        public string ext_lel_3 { get; set; }
        public string ext_o2_3 { get; set; }
        public string ext_h2s_3 { get; set; }
        public string ext_co_3 { get; set; }
        public string ext_other_3 { get; set; }
        public string ext_gas_tester_3 { get; set; }
        public string ext_gas_tester_approve_3 { get; set; }
        public string ext_work_leader_3 { get; set; }
        public string ext_work_leader_approve_3 { get; set; }
        public string ext_fo_3 { get; set; }
        public string ext_fo_delegate_3 { get; set; }
        public string ext_fo_approve_3 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_3 { get; set; }
        public string ext_remark_3 { get; set; }
        public Nullable<System.DateTime> ext_datetime_4 { get; set; }
        public string ext_lel_4 { get; set; }
        public string ext_o2_4 { get; set; }
        public string ext_h2s_4 { get; set; }
        public string ext_co_4 { get; set; }
        public string ext_other_4 { get; set; }
        public string ext_gas_tester_4 { get; set; }
        public string ext_gas_tester_approve_4 { get; set; }
        public string ext_work_leader_4 { get; set; }
        public string ext_work_leader_approve_4 { get; set; }
        public string ext_fo_4 { get; set; }
        public string ext_fo_delegate_4 { get; set; }
        public string ext_fo_approve_4 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_4 { get; set; }
        public string ext_remark_4 { get; set; }
        public Nullable<System.DateTime> ext_datetime_5 { get; set; }
        public string ext_lel_5 { get; set; }
        public string ext_o2_5 { get; set; }
        public string ext_h2s_5 { get; set; }
        public string ext_co_5 { get; set; }
        public string ext_other_5 { get; set; }
        public string ext_gas_tester_5 { get; set; }
        public string ext_gas_tester_approve_5 { get; set; }
        public string ext_work_leader_5 { get; set; }
        public string ext_work_leader_approve_5 { get; set; }
        public string ext_fo_5 { get; set; }
        public string ext_fo_delegate_5 { get; set; }
        public string ext_fo_approve_5 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_5 { get; set; }
        public string ext_remark_5 { get; set; }
        public Nullable<System.DateTime> ext_datetime_6 { get; set; }
        public string ext_lel_6 { get; set; }
        public string ext_o2_6 { get; set; }
        public string ext_h2s_6 { get; set; }
        public string ext_co_6 { get; set; }
        public string ext_other_6 { get; set; }
        public string ext_gas_tester_6 { get; set; }
        public string ext_gas_tester_approve_6 { get; set; }
        public string ext_work_leader_6 { get; set; }
        public string ext_work_leader_approve_6 { get; set; }
        public string ext_fo_6 { get; set; }
        public string ext_fo_delegate_6 { get; set; }
        public string ext_fo_approve_6 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_6 { get; set; }
        public string ext_remark_6 { get; set; }
        public Nullable<System.DateTime> ext_datetime_7 { get; set; }
        public string ext_lel_7 { get; set; }
        public string ext_o2_7 { get; set; }
        public string ext_h2s_7 { get; set; }
        public string ext_co_7 { get; set; }
        public string ext_other_7 { get; set; }
        public string ext_gas_tester_7 { get; set; }
        public string ext_gas_tester_approve_7 { get; set; }
        public string ext_work_leader_7 { get; set; }
        public string ext_work_leader_approve_7 { get; set; }
        public string ext_fo_7 { get; set; }
        public string ext_fo_delegate_7 { get; set; }
        public string ext_fo_approve_7 { get; set; }
        public Nullable<System.DateTime> ext_new_validity_7 { get; set; }
        public string ext_remark_7 { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual permit_to_work permit_to_work { get; set; }
    }
}
