//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loto_permit_to_work
    {
        public int id_loto { get; set; }
        public int id_permit { get; set; }
        public Nullable<int> holder_no { get; set; }
    
        public virtual permit_to_work permit_to_work { get; set; }
        public virtual loto_permit loto_permit { get; set; }
    }
}
