//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loto_permit
    {
        public loto_permit()
        {
            this.loto_coming_holder = new HashSet<loto_coming_holder>();
            this.loto_permit_to_work = new HashSet<loto_permit_to_work>();
            this.loto_point = new HashSet<loto_point>();
            this.loto_suspension = new HashSet<loto_suspension>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_glarf { get; set; }
        public string loto_no { get; set; }
        public string requestor { get; set; }
        public string supervisor { get; set; }
        public string work_location { get; set; }
        public string lock_box_no { get; set; }
        public Nullable<int> initial_pad_lock { get; set; }
        public Nullable<int> qty_pad_lock_usage { get; set; }
        public Nullable<int> balance { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_facility_owner { get; set; }
        public string approval_supervisor_signature { get; set; }
        public string approval_supervisor_signature_delegate { get; set; }
        public Nullable<System.DateTime> approval_supervisor_signature_date { get; set; }
        public string approval_fo_signature { get; set; }
        public Nullable<System.DateTime> approval_fo_signature_date { get; set; }
        public string approval_fo_signature_delegate { get; set; }
        public string oncoming_holder_1 { get; set; }
        public string oncoming_holder_2 { get; set; }
        public string oncoming_holder_3 { get; set; }
        public string oncoming_holder_4 { get; set; }
        public string oncoming_holder_5 { get; set; }
        public string oncoming_holder_6 { get; set; }
        public string oncoming_holder_7 { get; set; }
        public string approval_holder_1_signature { get; set; }
        public string approval_holder_2_signature { get; set; }
        public string approval_holder_3_signature { get; set; }
        public string approval_holder_4_signature { get; set; }
        public string approval_holder_5_signature { get; set; }
        public string approval_holder_6_signature { get; set; }
        public string approval_holder_7_signature { get; set; }
        public Nullable<System.DateTime> approval_holder_1_datetime { get; set; }
        public Nullable<System.DateTime> approval_holder_2_datetime { get; set; }
        public Nullable<System.DateTime> approval_holder_3_datetime { get; set; }
        public Nullable<System.DateTime> approval_holder_4_datetime { get; set; }
        public Nullable<System.DateTime> approval_holder_5_datetime { get; set; }
        public Nullable<System.DateTime> approval_holder_6_datetime { get; set; }
        public Nullable<System.DateTime> approval_holder_7_datetime { get; set; }
        public string approval_notes { get; set; }
        public Nullable<int> status { get; set; }
        public string new_coming_holder { get; set; }
        public Nullable<byte> requestor_ok { get; set; }
        public Nullable<byte> holder_2_ok { get; set; }
        public Nullable<byte> holder_3_ok { get; set; }
        public Nullable<byte> holder_4_ok { get; set; }
        public Nullable<byte> holder_5_ok { get; set; }
        public Nullable<byte> holder_6_ok { get; set; }
        public Nullable<byte> holder_7_ok { get; set; }
        public string cancellation_supervisor_signature { get; set; }
        public Nullable<System.DateTime> cancellation_supervisor_signature_date { get; set; }
        public string cancellation_holder_2_signature { get; set; }
        public Nullable<System.DateTime> cancellation_holder_2_signature_date { get; set; }
        public string cancellation_holder_3_signature { get; set; }
        public Nullable<System.DateTime> cancellation_holder_3_signature_date { get; set; }
        public string cancellation_holder_4_signature { get; set; }
        public Nullable<System.DateTime> cancellation_holder_4_signature_date { get; set; }
        public string cancellation_holder_5_signature { get; set; }
        public Nullable<System.DateTime> cancellation_holder_5_signature_date { get; set; }
        public string cancellation_holder_6_signature { get; set; }
        public Nullable<System.DateTime> cancellation_holder_6_signature_date { get; set; }
        public string cancellation_holder_7_signature { get; set; }
        public Nullable<System.DateTime> cancellation_holder_7_signature_date { get; set; }
        public string cancellation_fo_signature { get; set; }
        public Nullable<System.DateTime> cancellation_fo_signature_date { get; set; }
        public string cancellation_fo_signature_delegate { get; set; }
        public string cancellation_notes { get; set; }
        public string cancellation_facility_owner { get; set; }
        public Nullable<int> holder_1_glarf { get; set; }
        public Nullable<int> holder_2_glarf { get; set; }
        public Nullable<int> holder_3_glarf { get; set; }
        public Nullable<int> holder_4_glarf { get; set; }
        public Nullable<int> holder_5_glarf { get; set; }
        public Nullable<int> holder_6_glarf { get; set; }
        public Nullable<int> holder_7_glarf { get; set; }
    
        public virtual ICollection<loto_coming_holder> loto_coming_holder { get; set; }
        public virtual loto_glarf loto_glarf { get; set; }
        public virtual ICollection<loto_permit_to_work> loto_permit_to_work { get; set; }
        public virtual ICollection<loto_point> loto_point { get; set; }
        public virtual ICollection<loto_suspension> loto_suspension { get; set; }
    }
}
