//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loto_coming_holder
    {
        public int id { get; set; }
        public Nullable<int> id_loto { get; set; }
        public string holder_spv { get; set; }
        public Nullable<int> no_holder { get; set; }
        public string holder_sign_approval { get; set; }
        public Nullable<System.DateTime> holder_date_approval { get; set; }
        public string holder_sign_delegate_approval { get; set; }
        public string holder_sign_cancellation { get; set; }
        public Nullable<System.DateTime> holder_date_cancellation { get; set; }
        public string holder_sign_delegate_cancellation { get; set; }
        public string holder { get; set; }
    
        public virtual loto_permit loto_permit { get; set; }
    }
}
