//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loto_glarf_user
    {
        public int id { get; set; }
        public Nullable<int> id_glarf { get; set; }
        public string user { get; set; }
        public string user_application_signature { get; set; }
        public Nullable<System.DateTime> user_application_signature_date { get; set; }
        public string user_cancellation_signature { get; set; }
        public Nullable<System.DateTime> user_cancellation_signature_date { get; set; }
        public Nullable<byte> can_edit { get; set; }
    
        public virtual loto_glarf loto_glarf { get; set; }
    }
}
