//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loto_glarf
    {
        public loto_glarf()
        {
            this.loto_glarf_user = new HashSet<loto_glarf_user>();
            this.permit_to_work = new HashSet<permit_to_work>();
        }
    
        public int id { get; set; }
        public string requestor { get; set; }
        public string supervisor { get; set; }
        public string requestor_signature { get; set; }
        public string supervisor_signature { get; set; }
        public Nullable<int> id_loto_permit { get; set; }
        public string loto_no { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<loto_glarf_user> loto_glarf_user { get; set; }
        public virtual ICollection<permit_to_work> permit_to_work { get; set; }
        public virtual loto_permit loto_permit { get; set; }
    }
}
