//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loto_point
    {
        public int id { get; set; }
        public Nullable<int> id_loto { get; set; }
        public string tag_id { get; set; }
        public string description { get; set; }
        public string drawing_number { get; set; }
        public string loto_point_proposed { get; set; }
        public string loto_point_agreed { get; set; }
        public string applied_by { get; set; }
        public Nullable<System.DateTime> applied_by_time { get; set; }
        public string removed_by { get; set; }
        public Nullable<System.DateTime> removed_by_time { get; set; }
        public string remarks { get; set; }
        public string inspected_1 { get; set; }
        public string inspected_2 { get; set; }
        public string inspected_3 { get; set; }
        public string inspected_4 { get; set; }
        public string inspected_5 { get; set; }
        public string inspected_6 { get; set; }
        public string inspected_7 { get; set; }
        public Nullable<byte> is_removed { get; set; }
        public Nullable<byte> is_edited { get; set; }
        public Nullable<byte> is_set_empty { get; set; }
    
        public virtual loto_permit loto_permit { get; set; }
    }
}
