//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_delegate_fo
    {
        public int id { get; set; }
        public Nullable<int> id_mst_fo { get; set; }
        public Nullable<int> user_delegate_id { get; set; }
    
        public virtual mst_facility_owner mst_facility_owner { get; set; }
    }
}
