//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_no_inspection
    {
        public int id { get; set; }
        public string inspector_id { get; set; }
        public string no_inspection { get; set; }
        public Nullable<System.DateTime> valid_date { get; set; }
        public Nullable<int> id_inspection { get; set; }
    
        public virtual scaffolding_inspection scaffolding_inspection { get; set; }
    }
}
