//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_ex_disposal_location
    {
        public mst_ex_disposal_location()
        {
            this.excavation_disposal_location = new HashSet<excavation_disposal_location>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool is_delete { get; set; }
    
        public virtual ICollection<excavation_disposal_location> excavation_disposal_location { get; set; }
    }
}
