//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_erector
    {
        public int id { get; set; }
        public Nullable<int> id_employee { get; set; }
        public string certificate_no { get; set; }
        public Nullable<System.DateTime> valid_date { get; set; }
    }
}
