//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_radiographer
    {
        public int id { get; set; }
        public string employee { get; set; }
        public Nullable<int> level { get; set; }
        public string license_number { get; set; }
        public Nullable<System.DateTime> valid_date { get; set; }
    }
}
