//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permit_to_work
    {
        public permit_to_work()
        {
            this.confined_space = new HashSet<confined_space>();
            this.excavations = new HashSet<excavation>();
            this.fire_impairment = new HashSet<fire_impairment>();
            this.hira_document = new HashSet<hira_document>();
            this.hot_work = new HashSet<hot_work>();
            this.permit_to_work1 = new HashSet<permit_to_work>();
            this.radiographies = new HashSet<radiography>();
            this.safety_briefing = new HashSet<safety_briefing>();
            this.working_height = new HashSet<working_height>();
            this.loto_permit = new HashSet<loto_permit>();
        }
    
        public int id { get; set; }
        public string ptw_no { get; set; }
        public Nullable<System.DateTime> proposed_period_start { get; set; }
        public Nullable<System.DateTime> proposed_period_end { get; set; }
        public Nullable<int> dept_requestor { get; set; }
        public Nullable<int> section { get; set; }
        public string total_crew { get; set; }
        public Nullable<int> requestor_ptw_holder_no { get; set; }
        public string area { get; set; }
        public string work_location { get; set; }
        public string area_code { get; set; }
        public string work_order_no { get; set; }
        public string work_description { get; set; }
        public string notes { get; set; }
        public Nullable<byte> pre_job_1_spv { get; set; }
        public Nullable<byte> pre_job_2_spv { get; set; }
        public Nullable<byte> pre_job_3_spv { get; set; }
        public Nullable<byte> pre_job_4_spv { get; set; }
        public Nullable<byte> pre_job_5_spv { get; set; }
        public Nullable<byte> pre_job_6_spv { get; set; }
        public Nullable<byte> pre_job_7_spv { get; set; }
        public Nullable<byte> pre_job_1_fo { get; set; }
        public Nullable<byte> pre_job_2_fo { get; set; }
        public Nullable<byte> pre_job_3_fo { get; set; }
        public Nullable<byte> pre_job_4_fo { get; set; }
        public Nullable<byte> pre_job_5_fo { get; set; }
        public Nullable<byte> pre_job_6_fo { get; set; }
        public Nullable<byte> pre_job_7_fo { get; set; }
        public Nullable<byte> cancel_1_spv { get; set; }
        public Nullable<byte> cancel_2_spv { get; set; }
        public Nullable<byte> cancel_3_spv { get; set; }
        public Nullable<byte> cancel_4_spv { get; set; }
        public Nullable<byte> cancel_5_spv { get; set; }
        public Nullable<byte> cancel_6_spv { get; set; }
        public Nullable<byte> cancel_7_spv { get; set; }
        public Nullable<byte> cancel_1_fo { get; set; }
        public Nullable<byte> cancel_2_fo { get; set; }
        public Nullable<byte> cancel_3_fo { get; set; }
        public Nullable<byte> cancel_4_fo { get; set; }
        public Nullable<byte> cancel_5_fo { get; set; }
        public Nullable<byte> cancel_6_fo { get; set; }
        public Nullable<byte> cancel_7_fo { get; set; }
        public string pre_job_notes { get; set; }
        public string cancel_notes { get; set; }
        public Nullable<System.DateTime> validity_period_start { get; set; }
        public Nullable<System.DateTime> validity_period_end { get; set; }
        public Nullable<System.DateTime> cancellation_date { get; set; }
        public Nullable<int> loto_need { get; set; }
        public Nullable<int> loto_id { get; set; }
        public Nullable<int> loto_status { get; set; }
        public Nullable<int> csep_id { get; set; }
        public Nullable<int> csep_status { get; set; }
        public Nullable<int> hw_id { get; set; }
        public Nullable<int> hw_status { get; set; }
        public Nullable<int> fi_id { get; set; }
        public Nullable<int> fi_status { get; set; }
        public Nullable<int> ex_id { get; set; }
        public Nullable<int> ex_status { get; set; }
        public Nullable<int> wh_id { get; set; }
        public Nullable<int> wh_status { get; set; }
        public Nullable<int> rad_id { get; set; }
        public Nullable<int> rad_status { get; set; }
        public string acc_ptw_requestor { get; set; }
        public string acc_ptw_requestor_approve { get; set; }
        public string acc_supervisor { get; set; }
        public string acc_supervisor_delegate { get; set; }
        public string acc_supervisor_approve { get; set; }
        public string acc_assessor { get; set; }
        public string acc_assessor_delegate { get; set; }
        public string acc_assessor_approve { get; set; }
        public string acc_fo { get; set; }
        public string acc_fo_delegate { get; set; }
        public string acc_fo_approve { get; set; }
        public string can_ptw_requestor { get; set; }
        public string can_ptw_requestor_approve { get; set; }
        public string can_supervisor { get; set; }
        public string can_supervisor_delegate { get; set; }
        public string can_supervisor_approve { get; set; }
        public string can_assessor { get; set; }
        public string can_assessor_delegate { get; set; }
        public string can_assessor_approve { get; set; }
        public string can_fo { get; set; }
        public string can_fo_delegate { get; set; }
        public string can_fo_approve { get; set; }
        public Nullable<int> id_parent_ptw { get; set; }
        public Nullable<int> status { get; set; }
        public string hira_docs { get; set; }
        public string acc_notes_fo_ass { get; set; }
        public string acc_notes_ass_fo { get; set; }
        public string can_notes_ass_fo { get; set; }
        public Nullable<byte> is_guest { get; set; }
        public string guest_holder_no { get; set; }
        public Nullable<byte> requested_no { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual ICollection<confined_space> confined_space { get; set; }
        public virtual ICollection<excavation> excavations { get; set; }
        public virtual ICollection<fire_impairment> fire_impairment { get; set; }
        public virtual ICollection<hira_document> hira_document { get; set; }
        public virtual ICollection<hot_work> hot_work { get; set; }
        public virtual loto_glarf loto_glarf { get; set; }
        public virtual mst_department mst_department { get; set; }
        public virtual mst_ptw_holder_no mst_ptw_holder_no { get; set; }
        public virtual mst_section mst_section { get; set; }
        public virtual ICollection<permit_to_work> permit_to_work1 { get; set; }
        public virtual permit_to_work permit_to_work2 { get; set; }
        public virtual ICollection<radiography> radiographies { get; set; }
        public virtual ICollection<safety_briefing> safety_briefing { get; set; }
        public virtual ICollection<working_height> working_height { get; set; }
        public virtual ICollection<loto_permit> loto_permit { get; set; }
    }
}
