//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rca_pre_task
    {
        public int id { get; set; }
        public Nullable<int> id_rca { get; set; }
        public string task { get; set; }
        public Nullable<int> pic { get; set; }
        public Nullable<System.DateTime> target_date { get; set; }
        public string data_to_collect { get; set; }
        public Nullable<int> id_category { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual rca_preserve_category rca_preserve_category { get; set; }
    }
}
