//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rca_csf_conector
    {
        public int id { get; set; }
        public Nullable<int> id_rca { get; set; }
        public Nullable<int> id_csf { get; set; }
        public string custom { get; set; }
    
        public virtual rca rca { get; set; }
    }
}
