//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class safety_briefing
    {
        public safety_briefing()
        {
            this.safety_briefing_user = new HashSet<safety_briefing_user>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_ptw { get; set; }
        public string section { get; set; }
        public string work_area { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string topic { get; set; }
        public string hazard { get; set; }
        public string control_method { get; set; }
        public Nullable<int> status { get; set; }
        public string requestor { get; set; }
    
        public virtual ICollection<safety_briefing_user> safety_briefing_user { get; set; }
        public virtual permit_to_work permit_to_work { get; set; }
    }
}
