//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class safety_briefing_user
    {
        public int id { get; set; }
        public Nullable<int> id_safety_briefing { get; set; }
        public string user { get; set; }
        public string id_badge { get; set; }
        public string user_signature { get; set; }
    
        public virtual safety_briefing safety_briefing { get; set; }
    }
}
