//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scaffolding_inspection
    {
        public scaffolding_inspection()
        {
            this.mst_no_inspection = new HashSet<mst_no_inspection>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_inspection { get; set; }
        public string type_scaffold { get; set; }
        public string duties_scaffold { get; set; }
        public string pupose_scaffold { get; set; }
        public string location { get; set; }
        public string name_scaffolder { get; set; }
        public string base_ground_good { get; set; }
        public string base_ground_poor { get; set; }
        public string base_ground_remark { get; set; }
        public string base_concrete_good { get; set; }
        public string base_concrete_poor { get; set; }
        public string base_concrete_remark { get; set; }
        public string base_sole_plate_good { get; set; }
        public string base_sole_plate_poor { get; set; }
        public string base_sole_plate_remark { get; set; }
        public string base_base_plate_good { get; set; }
        public string base_base_plate_poor { get; set; }
        public string base_base_plate_remark { get; set; }
        public string base_adj_sole_plate_good { get; set; }
        public string base_adj_sole_plate_poor { get; set; }
        public string base_adj_sole_plate_remark { get; set; }
        public string standard_diameter_good { get; set; }
        public string standard_diameter_poor { get; set; }
        public string standard_diameter_remark { get; set; }
        public string standard_length_good { get; set; }
        public string standard_length_poor { get; set; }
        public string standard_length_remark { get; set; }
        public string standard_leveling_good { get; set; }
        public string standard_leveling_poor { get; set; }
        public string standard_leveling_remark { get; set; }
        public string standard_couplers_good { get; set; }
        public string standard_couplers_poor { get; set; }
        public string standard_couplers_remark { get; set; }
        public string standard_pin_good { get; set; }
        public string standard_pin_poor { get; set; }
        public string standard_pin_remark { get; set; }
        public string ledger_diameter_good { get; set; }
        public string ledger_diameter_poor { get; set; }
        public string ledger_diameter_remark { get; set; }
        public string ledger_length_good { get; set; }
        public string ledger_length_poor { get; set; }
        public string ledger_length_remark { get; set; }
        public string ledger_leveling_good { get; set; }
        public string ledger_leveling_poor { get; set; }
        public string ledger_leveling_remark { get; set; }
        public string ledger_couplers_good { get; set; }
        public string ledger_couplers_poor { get; set; }
        public string ledger_couplers_remark { get; set; }
        public string ledger_sleeve_couplers_good { get; set; }
        public string ledger_sleeve_couplers_poor { get; set; }
        public string ledger_sleeve_couplers_remark { get; set; }
        public string transom_diameter_good { get; set; }
        public string transom_diameter_poor { get; set; }
        public string transom_diameter_remark { get; set; }
        public string transom_length_good { get; set; }
        public string transom_length_poor { get; set; }
        public string transom_length_remark { get; set; }
        public string transom_leveling_good { get; set; }
        public string transom_leveling_poor { get; set; }
        public string transom_leveling_remark { get; set; }
        public string transom_couplers_good { get; set; }
        public string transom_couplers_poor { get; set; }
        public string transom_couplers_remark { get; set; }
        public string transom_sleeve_couplers_good { get; set; }
        public string transom_sleeve_couplers_poor { get; set; }
        public string transom_sleeve_couplers_remark { get; set; }
        public string putlog_diameter_good { get; set; }
        public string putlog_diameter_poor { get; set; }
        public string putlog_diameter_remark { get; set; }
        public string putlog_length_good { get; set; }
        public string putlog_length_poor { get; set; }
        public string putlog_length_remark { get; set; }
        public string putlog_leveling_good { get; set; }
        public string putlog_leveling_poor { get; set; }
        public string putlog_leveling_remark { get; set; }
        public string bracing_diameter_good { get; set; }
        public string bracing_diameter_poor { get; set; }
        public string bracing_diameter_remark { get; set; }
        public string bracing_length_good { get; set; }
        public string bracing_length_poor { get; set; }
        public string bracing_length_remark { get; set; }
        public string bracing_pins_good { get; set; }
        public string bracing_pins_poor { get; set; }
        public string bracing_pins_remark { get; set; }
        public string bracing_couplers_good { get; set; }
        public string bracing_couplers_poor { get; set; }
        public string bracing_couplers_remark { get; set; }
        public string guardrail_ledger_diameter_good { get; set; }
        public string guardrail_ledger_diameter_poor { get; set; }
        public string guardrail_ledger_diameter_remark { get; set; }
        public string guardrail_ledger_length_good { get; set; }
        public string guardrail_ledger_length_poor { get; set; }
        public string guardrail_ledger_length_remark { get; set; }
        public string guardrail_ledger_leveling_good { get; set; }
        public string guardrail_ledger_leveling_poor { get; set; }
        public string guardrail_ledger_leveling_remark { get; set; }
        public string guardrail_ledger_couplers_good { get; set; }
        public string guardrail_ledger_couplers_poor { get; set; }
        public string guardrail_ledger_couplers_remark { get; set; }
        public string guardrail_ledger_sleeve_couplers_good { get; set; }
        public string guardrail_ledger_sleeve_couplers_poor { get; set; }
        public string guardrail_ledger_sleeve_couplers_remark { get; set; }
        public string guardrail_transom_diameter_good { get; set; }
        public string guardrail_transom_diameter_poor { get; set; }
        public string guardrail_transom_diameter_remark { get; set; }
        public string guardrail_transom_length_good { get; set; }
        public string guardrail_transom_length_poor { get; set; }
        public string guardrail_transom_length_remark { get; set; }
        public string guardrail_transom_leveling_good { get; set; }
        public string guardrail_transom_leveling_poor { get; set; }
        public string guardrail_transom_leveling_remark { get; set; }
        public string guardrail_transom_couplers_good { get; set; }
        public string guardrail_transom_couplers_poor { get; set; }
        public string guardrail_transom_couplers_remark { get; set; }
        public string guardrail_transom_sleeve_couplers_good { get; set; }
        public string guardrail_transom_sleeve_couplers_poor { get; set; }
        public string guardrail_transom_sleeve_couplers_remark { get; set; }
        public string platform_condition_good { get; set; }
        public string platform_condition_poor { get; set; }
        public string platform_condition_remark { get; set; }
        public string platform_length_good { get; set; }
        public string platform_length_poor { get; set; }
        public string platform_length_remark { get; set; }
        public string platform_width_good { get; set; }
        public string platform_width_poor { get; set; }
        public string platform_width_remark { get; set; }
        public string platform_clearance_good { get; set; }
        public string platform_clearance_poor { get; set; }
        public string platform_clearance_remark { get; set; }
        public string platform_lashing_good { get; set; }
        public string platform_lashing_poor { get; set; }
        public string platform_lashing_remark { get; set; }
        public string platform_deflection_good { get; set; }
        public string platform_deflection_poor { get; set; }
        public string platform_deflection_remark { get; set; }
        public string toeboard_condition_good { get; set; }
        public string toeboard_condition_poor { get; set; }
        public string toeboard_condition_remark { get; set; }
        public string toeboard_length_good { get; set; }
        public string toeboard_length_poor { get; set; }
        public string toeboard_length_remark { get; set; }
        public string toeboard_height_good { get; set; }
        public string toeboard_height_poor { get; set; }
        public string toeboard_height_remark { get; set; }
        public string toeboard_clearance_good { get; set; }
        public string toeboard_clearance_poor { get; set; }
        public string toeboard_clearance_remark { get; set; }
        public string toeboard_lashing_good { get; set; }
        public string toeboard_lashing_poor { get; set; }
        public string toeboard_lashing_remark { get; set; }
        public string aluminium_ladder_condition_good { get; set; }
        public string aluminium_ladder_condition_poor { get; set; }
        public string aluminium_ladder_condition_remark { get; set; }
        public string aluminium_ladder_length_good { get; set; }
        public string aluminium_ladder_length_poor { get; set; }
        public string aluminium_ladder_length_remark { get; set; }
        public string aluminium_ladder_height_good { get; set; }
        public string aluminium_ladder_height_poor { get; set; }
        public string aluminium_ladder_height_remark { get; set; }
        public string aluminium_ladder_putlog_good { get; set; }
        public string aluminium_ladder_putlog_poor { get; set; }
        public string aluminium_ladder_putlog_remark { get; set; }
        public string aluminium_ladder_angle_good { get; set; }
        public string aluminium_ladder_angle_poor { get; set; }
        public string aluminium_ladder_angle_remark { get; set; }
        public string ladder_tube_condition_good { get; set; }
        public string ladder_tube_condition_poor { get; set; }
        public string ladder_tube_condition_remark { get; set; }
        public string ladder_tube_diameter_good { get; set; }
        public string ladder_tube_diameter_poor { get; set; }
        public string ladder_tube_diameter_remark { get; set; }
        public string ladder_tube_height_good { get; set; }
        public string ladder_tube_height_poor { get; set; }
        public string ladder_tube_height_remark { get; set; }
        public string ladder_tube_putlog_good { get; set; }
        public string ladder_tube_putlog_poor { get; set; }
        public string ladder_tube_putlog_remark { get; set; }
        public string ladder_tube_angle_good { get; set; }
        public string ladder_tube_angle_poor { get; set; }
        public string ladder_tube_angle_remark { get; set; }
        public string ladder_tube_coupler_good { get; set; }
        public string ladder_tube_coupler_poor { get; set; }
        public string ladder_tube_coupler_remark { get; set; }
        public string gin_wheel_condition_good { get; set; }
        public string gin_wheel_condition_poor { get; set; }
        public string gin_wheel_condition_remark { get; set; }
        public string gin_wheel_swl_good { get; set; }
        public string gin_wheel_swl_poor { get; set; }
        public string gin_wheel_swl_remark { get; set; }
        public string gin_wheel_hoist_good { get; set; }
        public string gin_wheel_hoist_poor { get; set; }
        public string gin_wheel_hoist_remark { get; set; }
        public string gin_wheel_catch_good { get; set; }
        public string gin_wheel_catch_poor { get; set; }
        public string gin_wheel_catch_remark { get; set; }
        public string gin_wheel_clamp_good { get; set; }
        public string gin_wheel_clamp_poor { get; set; }
        public string gin_wheel_clamp_remark { get; set; }
        public string ties_condition_good { get; set; }
        public string ties_condition_poor { get; set; }
        public string ties_condition_remark { get; set; }
        public string ties_pipes_good { get; set; }
        public string ties_pipes_poor { get; set; }
        public string ties_pipes_remark { get; set; }
        public string access_ladder_access_good { get; set; }
        public string access_ladder_access_poor { get; set; }
        public string access_ladder_access_remark { get; set; }
        public string access_ladder_landing_platform_good { get; set; }
        public string access_ladder_landing_platform_poor { get; set; }
        public string access_ladder_landing_platform_remark { get; set; }
        public string access_ladder_safety_good { get; set; }
        public string access_ladder_safety_poor { get; set; }
        public string access_ladder_safety_remark { get; set; }
        public string general_surface_leveling_good { get; set; }
        public string general_surface_leveling_poor { get; set; }
        public string general_surface_leveling_remark { get; set; }
        public string general_surface_safety_good { get; set; }
        public string general_surface_safety_poor { get; set; }
        public string general_surface_safety_remark { get; set; }
        public string others_text { get; set; }
        public string others_good { get; set; }
        public string others_poor { get; set; }
        public string others_remark { get; set; }
        public string safety_recommendation { get; set; }
    
        public virtual ICollection<mst_no_inspection> mst_no_inspection { get; set; }
    }
}
