//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class star_energy_ptwEntities : DbContext
    {
        public star_energy_ptwEntities()
            : base("name=star_energy_ptwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<confined_space> confined_space { get; set; }
        public DbSet<fire_impairment> fire_impairment { get; set; }
        public DbSet<hira_document> hira_document { get; set; }
        public DbSet<hot_work> hot_work { get; set; }
        public DbSet<loto_glarf> loto_glarf { get; set; }
        public DbSet<loto_glarf_user> loto_glarf_user { get; set; }
        public DbSet<loto_point> loto_point { get; set; }
        public DbSet<mst_assessor> mst_assessor { get; set; }
        public DbSet<mst_department> mst_department { get; set; }
        public DbSet<mst_dept_head_fo> mst_dept_head_fo { get; set; }
        public DbSet<mst_ei> mst_ei { get; set; }
        public DbSet<mst_erector> mst_erector { get; set; }
        public DbSet<mst_facilities> mst_facilities { get; set; }
        public DbSet<mst_lock_box> mst_lock_box { get; set; }
        public DbSet<mst_loto_point> mst_loto_point { get; set; }
        public DbSet<mst_ptw_holder_no> mst_ptw_holder_no { get; set; }
        public DbSet<mst_radiation_po> mst_radiation_po { get; set; }
        public DbSet<mst_radiographer> mst_radiographer { get; set; }
        public DbSet<mst_safety_officer> mst_safety_officer { get; set; }
        public DbSet<mst_section> mst_section { get; set; }
        public DbSet<permit_log> permit_log { get; set; }
        public DbSet<radiography> radiographies { get; set; }
        public DbSet<loto_suspension_holder> loto_suspension_holder { get; set; }
        public DbSet<safety_briefing_user> safety_briefing_user { get; set; }
        public DbSet<safety_briefing> safety_briefing { get; set; }
        public DbSet<mst_inspector> mst_inspector { get; set; }
        public DbSet<mst_no_inspection> mst_no_inspection { get; set; }
        public DbSet<scaffolding_inspection> scaffolding_inspection { get; set; }
        public DbSet<mst_facility_owner> mst_facility_owner { get; set; }
        public DbSet<mst_area_code> mst_area_code { get; set; }
        public DbSet<loto_coming_holder> loto_coming_holder { get; set; }
        public DbSet<email_error> email_error { get; set; }
        public DbSet<mst_delegate_fo> mst_delegate_fo { get; set; }
        public DbSet<loto_suspension> loto_suspension { get; set; }
        public DbSet<loto_permit> loto_permit { get; set; }
        public DbSet<working_height> working_height { get; set; }
        public DbSet<mst_ex_disposal_location> mst_ex_disposal_location { get; set; }
        public DbSet<mst_enviro_officer> mst_enviro_officer { get; set; }
        public DbSet<excavation> excavations { get; set; }
        public DbSet<excavation_disposal_location> excavation_disposal_location { get; set; }
        public DbSet<permit_to_work> permit_to_work { get; set; }
    }
}
