//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermitToWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class star_energy_ptwEntities : DbContext
    {
        public star_energy_ptwEntities()
            : base("name=star_energy_ptwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<hira_document> hira_document { get; set; }
        public DbSet<permit_log> permit_log { get; set; }
        public DbSet<mst_department> mst_department { get; set; }
        public DbSet<mst_section> mst_section { get; set; }
        public DbSet<mst_ptw_holder_no> mst_ptw_holder_no { get; set; }
        public DbSet<mst_assessor> mst_assessor { get; set; }
        public DbSet<mst_facility_owner> mst_facility_owner { get; set; }
        public DbSet<hot_work> hot_work { get; set; }
        public DbSet<permit_to_work> permit_to_work { get; set; }
        public DbSet<mst_dept_head_fo> mst_dept_head_fo { get; set; }
        public DbSet<mst_safety_officer> mst_safety_officer { get; set; }
        public DbSet<fire_impairment> fire_impairment { get; set; }
        public DbSet<radiography> radiographies { get; set; }
        public DbSet<mst_radiographer> mst_radiographer { get; set; }
        public DbSet<mst_radiation_po> mst_radiation_po { get; set; }
        public DbSet<mst_erector> mst_erector { get; set; }
        public DbSet<mst_inspector> mst_inspector { get; set; }
        public DbSet<working_height> working_height { get; set; }
    }
}
